author           = Byakuren
#depends          =
description      = """ 
A library for managing global player state, 
such as physics overrides or player visual size.
"""
name             = player_monoids
optional_depends = 
title            = IA Player Monoids
